//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jg.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jg.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 .jgc 的本地化字符串。
        /// </summary>
        internal static string CourseExtension {
            get {
                return ResourceManager.GetString("CourseExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .jgs 的本地化字符串。
        /// </summary>
        internal static string CourseExtensionServer {
            get {
                return ResourceManager.GetString("CourseExtensionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (景格电子书)*.jgc|*.jgc 的本地化字符串。
        /// </summary>
        internal static string ExtensionFilter {
            get {
                return ResourceManager.GetString("ExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (动画)*.swf|*.swf 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerAnimationFilter {
            get {
                return ResourceManager.GetString("ExtensionServerAnimationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (文档)*.pdf|*.pdf|(文档)*.doc|*.doc|(文档)*.docx|*.docx|(文档)*.xls|*.xls|(文档)*.xlsx|*.xlsx|(文档)*.ppt|*.ppt|(文档)*.pptx|*.pptx 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerDocumentFilter {
            get {
                return ResourceManager.GetString("ExtensionServerDocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (景格电子书头文件)*.jgs|*.jgs 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerFilter {
            get {
                return ResourceManager.GetString("ExtensionServerFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (HTML5)*.htm|*.htm|(HTML5)*.html|*.html 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerHTMLFilter {
            get {
                return ResourceManager.GetString("ExtensionServerHTMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (图像*.png)|*.png|(图像*.jpg)|*.jpg|(图像*.jpeg)|*.jpeg|(图像*.bmp)|*.bmp 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerImgFilter {
            get {
                return ResourceManager.GetString("ExtensionServerImgFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (unity3d)*.unity3d|*.unity3d 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerModel3DFilter {
            get {
                return ResourceManager.GetString("ExtensionServerModel3DFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (视频文件)*.mp4|*.mp4|(视频文件)*.wmv|*.wmv|(视频文件)*.avi|*.avi 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerMovieFilter {
            get {
                return ResourceManager.GetString("ExtensionServerMovieFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (声音文件)*.mp3|*.mp3 的本地化字符串。
        /// </summary>
        internal static string ExtensionServerSoundFilter {
            get {
                return ResourceManager.GetString("ExtensionServerSoundFilter", resourceCulture);
            }
        }
    }
}
